# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2018-12-25 16:06
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('music', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='song',
            name='song_favorite',
            field=models.BooleanField(default=False),
        ),
    ]
